# docker-compose.yml

version: "3.9"
services:
  postgres:
    container_name: db-useit
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-useit
    expose:
     - 5432
    ports:
      - '5432:5432'
    volumes:
      - useit-db:/var/lib/postgresql/data

  useit:
    container_name: api-useit
    build:
      context: .
    environment:
      DB_SCHEMA: db-useit
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '5000:5000'

volumes:
  useit-db: